version: '3'

services:
  app:
    container_name: leitor_xml_backend_container
    build:
      context: .
      dockerfile: .Dockerfile
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/leitor-xml-backend